# @format

name: Sync Repos

on:
  push:
    branches:
      - main
  # You can add more triggers, such as scheduled events
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Push to destination repository
        run: |
          git config --global user.email "your email"
          git config --global user.name "your user name"
          git clone https://${{ env.SOURCE_ORG_NAME }}:${{ secrets.SOURCE_PAT }}@github.com/${{ env.SOURCE_ORG_NAME }}/TestSync.git
          cd TestSync
          git remote add ${{ env.TARGET_REPO_NAME }} https://${{ env.TARGET_ORG_NAME }}:${{ secrets.TARGET_PAT }}@github.com/${{ env.TARGET_ORG_NAME }}/${{ env.TARGET_REPO_NAME }}.git
          git remote update
          git merge ${{ env.TARGET_REPO_NAME }}/main
          git push origin main
        env:
          SOURCE_PAT: ${{ secrets.SOURCEPAT }}
          TARGET_PAT: ${{ secrets.TARGETPAT }}
          SOURCE_ORG_NAME: HGWilson
          TARGET_ORG_NAME: TWBug
          TARGET_REPO_NAME: TestSync
